//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGen.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiGen.Localization.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft.
        /// </summary>
        public static string FeetAbbreviation {
            get {
                return ResourceManager.GetString("FeetAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge.
        /// </summary>
        public static string FingerboardEnd_Bridge {
            get {
                return ResourceManager.GetString("FingerboardEnd.Bridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nut.
        /// </summary>
        public static string FingerboardEnd_Nut {
            get {
                return ResourceManager.GetString("FingerboardEnd.Nut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bass.
        /// </summary>
        public static string FingerboardSide_Bass {
            get {
                return ResourceManager.GetString("FingerboardSide.Bass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treble.
        /// </summary>
        public static string FingerboardSide_Treble {
            get {
                return ResourceManager.GetString("FingerboardSide.Treble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string InchAbbreviation {
            get {
                return ResourceManager.GetString("InchAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string NoteName_A {
            get {
                return ResourceManager.GetString("NoteName.A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G♯/A♭.
        /// </summary>
        public static string NoteName_Ab {
            get {
                return ResourceManager.GetString("NoteName.Ab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string NoteName_B {
            get {
                return ResourceManager.GetString("NoteName.B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A♯/B♭.
        /// </summary>
        public static string NoteName_Bb {
            get {
                return ResourceManager.GetString("NoteName.Bb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string NoteName_C {
            get {
                return ResourceManager.GetString("NoteName.C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string NoteName_D {
            get {
                return ResourceManager.GetString("NoteName.D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C♯/D♭.
        /// </summary>
        public static string NoteName_Db {
            get {
                return ResourceManager.GetString("NoteName.Db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string NoteName_E {
            get {
                return ResourceManager.GetString("NoteName.E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D♯/E♭.
        /// </summary>
        public static string NoteName_Eb {
            get {
                return ResourceManager.GetString("NoteName.Eb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        public static string NoteName_F {
            get {
                return ResourceManager.GetString("NoteName.F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        public static string NoteName_G {
            get {
                return ResourceManager.GetString("NoteName.G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F♯/G♭.
        /// </summary>
        public static string NoteName_Gb {
            get {
                return ResourceManager.GetString("NoteName.Gb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiscale.
        /// </summary>
        public static string ScaleLengthMode_Multiscale {
            get {
                return ResourceManager.GetString("ScaleLengthMode.Multiscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per-string.
        /// </summary>
        public static string ScaleLengthMode_PerString {
            get {
                return ResourceManager.GetString("ScaleLengthMode.PerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string ScaleLengthMode_Single {
            get {
                return ResourceManager.GetString("ScaleLengthMode.Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale length for &apos;{0}&apos; side is not configured..
        /// </summary>
        public static string ScaleLengthSideNotConfigured {
            get {
                return ResourceManager.GetString("ScaleLengthSideNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale length for string {0} is not configured..
        /// </summary>
        public static string ScaleLengthStringNotConfigured {
            get {
                return ResourceManager.GetString("ScaleLengthStringNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale length is not configured..
        /// </summary>
        public static string SingleScaleNotConfigured {
            get {
                return ResourceManager.GetString("SingleScaleNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String spacing is not configured properly at the {0}..
        /// </summary>
        public static string StringSpacingConfigInvalid {
            get {
                return ResourceManager.GetString("StringSpacingConfigInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use manual center alignment for both ends..
        /// </summary>
        public static string StringSpacingManualAlignmentBothEnds {
            get {
                return ResourceManager.GetString("StringSpacingManualAlignmentBothEnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing at the {0} is set to manual but the alignment was not specified..
        /// </summary>
        public static string StringSpacingManualAlignmentRatioNotSet {
            get {
                return ResourceManager.GetString("StringSpacingManualAlignmentRatioNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop.
        /// </summary>
        public static string Tuning_Drop {
            get {
                return ResourceManager.GetString("Tuning.Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop {0}.
        /// </summary>
        public static string Tuning_DropFormat {
            get {
                return ResourceManager.GetString("Tuning.DropFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Tuning_Open {
            get {
                return ResourceManager.GetString("Tuning.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open {0}.
        /// </summary>
        public static string Tuning_OpenFormat {
            get {
                return ResourceManager.GetString("Tuning.OpenFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Tuning_Standard {
            get {
                return ResourceManager.GetString("Tuning.Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard {0}.
        /// </summary>
        public static string Tuning_StandardFormat {
            get {
                return ResourceManager.GetString("Tuning.StandardFormat", resourceCulture);
            }
        }
    }
}
