//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGen.Lang {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Help {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Help() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiGen.Lang.Help", typeof(Help).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sets the amount of skew between bass and treble strings.
        ///Use this to create fanned frets even when all strings share the same scale length.
        ///Positive values angle the frets one way, negative values the other. Leave blank for no skew..
        /// </summary>
        public static string BassTrebleSkew_Help {
            get {
                return ResourceManager.GetString("BassTrebleSkew_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accounts for the thickness of each string when calculating margins. 
        ///When enabled, the distance is measured from the edge of the string to the edge of the fingerboard, rather than from the string center..
        /// </summary>
        public static string CompensateForStrings_Help {
            get {
                return ResourceManager.GetString("CompensateForStrings_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Length to continue the fingerboard after the last fret.
        ///This extends the fingerboard body beyond the fretted area..
        /// </summary>
        public static string FingerboardExtension_Help {
            get {
                return ResourceManager.GetString("FingerboardExtension_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select whether the instrument layout is for a right-handed or left-handed player..
        /// </summary>
        public static string Handedness_Help {
            get {
                return ResourceManager.GetString("Handedness_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This value determines which kind of instrument you are designing. 
        ///Selecting an instrument type enables info buttons next to certain fields, showing common values and suggestions specific to that instrument..
        /// </summary>
        public static string InstrumentType_Help {
            get {
                return ResourceManager.GetString("InstrumentType_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose how the strings are positioned relative to the center line:
        ///• **Outer Strings**: Centers the outermost strings equally from the center line.
        ///• **Middle Strings**: Aligns the middle string(s) to the center line.
        ///• **Fingerboard**: Centers by the fingerboard edges (same as Outer Strings when margins are equal).
        ///• **Symmetric Strings**: *(Multiscale only)* Adjusts spacing to maintain symmetric layout at both nut and bridge.
        ///• **Symmetric Fingerboard**: *(Multiscale only)* Like Symmetric Strings, bu [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string LayoutCenterAlignment_Help {
            get {
                return ResourceManager.GetString("LayoutCenterAlignment_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose how to apply fingerboard margins:
        ///• **Uniform**: Use the same margin for all sides and ends.
        ///• **By End**: Set different margins for the nut and the bridge.
        ///• **By Side**: Set different margins for the bass and treble sides.
        ///• **Individual**: Manually set each of the four margins..
        /// </summary>
        public static string MarginMode_Help {
            get {
                return ResourceManager.GetString("MarginMode_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set the total number of strings for your instrument..
        /// </summary>
        public static string NumberOfStrings_Help {
            get {
                return ResourceManager.GetString("NumberOfStrings_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Controls which fret is straight (perpendicular to centerline) on a multiscale instrument.
        ///Enter any value from 0-100 or select a fret to align from the dropdown.
        ///Higher values make frets &quot;point&quot; more toward the bridge, lower values toward the nut..
        /// </summary>
        public static string ScaleLength_MultiScaleRatio {
            get {
                return ResourceManager.GetString("ScaleLength_MultiScaleRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose the scale length mode:
        ///• **Single**: A single scale length for all strings.
        ///• **Multiscale**: A separate scale length for treble and bass strings.
        ///• **Per-string**: A separate scale length for each string..
        /// </summary>
        public static string ScaleLengthMode_Help {
            get {
                return ResourceManager.GetString("ScaleLengthMode_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose how strings are spaced on the instrument:
        ///• **Proportional**: Strings are spaced so the free space between each string is equal, taking into account the thickness (gauge) of each string.
        ///• **Center to Center**: Strings are spaced so the distance from the center of one string to the center of the next is equal, regardless of string gauge.
        ///• **Manual**: String positions are set manually. The spacing mode is ignored, and you can place each string exactly where you want..
        /// </summary>
        public static string StringSpacingMode_Help {
            get {
                return ResourceManager.GetString("StringSpacingMode_Help", resourceCulture);
            }
        }
    }
}
