//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGen.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Help {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Help() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiGen.Lang.Help", typeof(Help).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the amount of skew between bass and treble strings.
        ///Use this to create fanned frets even when all strings share the same scale length.
        ///Positive values angle the frets one way, negative values the other. Leave blank for no skew..
        /// </summary>
        public static string BassTrebleSkew_Help {
            get {
                return ResourceManager.GetString("BassTrebleSkew_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez si la disposition de l&apos;instrument est destinée à un joueur droitier ou gaucher..
        /// </summary>
        public static string Handedness_Help {
            get {
                return ResourceManager.GetString("Handedness_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the total number of strings for your instrument..
        /// </summary>
        public static string NumberOfStrings_Help {
            get {
                return ResourceManager.GetString("NumberOfStrings_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the scale length mode:
        ///• **Single**: A single scale length for all strings.
        ///• **Multiscale**: A separate scale length for treble and bass strings.
        ///• **Per-string**: A separate scale length for each string..
        /// </summary>
        public static string ScaleLengthMode_Help {
            get {
                return ResourceManager.GetString("ScaleLengthMode_Help", resourceCulture);
            }
        }
    }
}
