//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGen.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiGen.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string AppLanguage_English {
            get {
                return ResourceManager.GetString("AppLanguage.English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string AppLanguage_French {
            get {
                return ResourceManager.GetString("AppLanguage.French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string AppLanguage_German {
            get {
                return ResourceManager.GetString("AppLanguage.German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string AppLanguage_Spanish {
            get {
                return ResourceManager.GetString("AppLanguage.Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string AppLanguage_System {
            get {
                return ResourceManager.GetString("AppLanguage.System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string AppTheme_Dark {
            get {
                return ResourceManager.GetString("AppTheme.Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string AppTheme_Light {
            get {
                return ResourceManager.GetString("AppTheme.Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string AppTheme_System {
            get {
                return ResourceManager.GetString("AppTheme.System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string CourseLabel {
            get {
                return ResourceManager.GetString("CourseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today {0}.
        /// </summary>
        public static string DateLabel_Today {
            get {
                return ResourceManager.GetString("DateLabel.Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday {0}.
        /// </summary>
        public static string DateLabel_Yesterday {
            get {
                return ResourceManager.GetString("DateLabel.Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Dialog_Button_Cancel {
            get {
                return ResourceManager.GetString("Dialog.Button.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Dialog_Button_No {
            get {
                return ResourceManager.GetString("Dialog.Button.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Dialog_Button_OK {
            get {
                return ResourceManager.GetString("Dialog.Button.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Dialog_Button_Yes {
            get {
                return ResourceManager.GetString("Dialog.Button.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to &quot;{0}&quot; before closing?.
        /// </summary>
        public static string Dialog_SaveChanges_Message {
            get {
                return ResourceManager.GetString("Dialog.SaveChanges.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        public static string Dialog_SaveChanges_Title {
            get {
                return ResourceManager.GetString("Dialog.SaveChanges.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisions.
        /// </summary>
        public static string EditFretsDialog_EqualTemperamentStepsHeader {
            get {
                return ResourceManager.GetString("EditFretsDialog.EqualTemperamentStepsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of equal divisions of the octave used for fret placement when the temperament is equal. 12 is the standard western system. Higher values can be used for microtonal layouts..
        /// </summary>
        public static string EditFretsDialog_EqualTemperamentStepsTooltip {
            get {
                return ResourceManager.GetString("EditFretsDialog.EqualTemperamentStepsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        public static string EditFretsDialog_GlobalLabel {
            get {
                return ResourceManager.GetString("EditFretsDialog.GlobalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global fret settings.
        /// </summary>
        public static string EditFretsDialog_GlobalSettingsHeader {
            get {
                return ResourceManager.GetString("EditFretsDialog.GlobalSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per-string settings can override fret count, starting fret, temperament, and equal temperament steps..
        /// </summary>
        public static string EditFretsDialog_OverrideInfo {
            get {
                return ResourceManager.GetString("EditFretsDialog.OverrideInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start fret.
        /// </summary>
        public static string EditFretsDialog_StartingFretHeader {
            get {
                return ResourceManager.GetString("EditFretsDialog.StartingFretHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting fret index for this string or course. 0 means the nut is the starting position. Positive values start after the nut. Negative values add one or more frets before the nut..
        /// </summary>
        public static string EditFretsDialog_StartingFretTooltip {
            get {
                return ResourceManager.GetString("EditFretsDialog.StartingFretTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strings.
        /// </summary>
        public static string EditFretsDialog_StringCountSuffix {
            get {
                return ResourceManager.GetString("EditFretsDialog.StringCountSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String / course.
        /// </summary>
        public static string EditFretsDialog_StringOrCourseHeader {
            get {
                return ResourceManager.GetString("EditFretsDialog.StringOrCourseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperament.
        /// </summary>
        public static string EditFretsDialog_TemperamentHeader {
            get {
                return ResourceManager.GetString("EditFretsDialog.TemperamentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fret Configuration.
        /// </summary>
        public static string EditFretsDialog_Title {
            get {
                return ResourceManager.GetString("EditFretsDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use global.
        /// </summary>
        public static string EditFretsDialog_UseGlobal {
            get {
                return ResourceManager.GetString("EditFretsDialog.UseGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left handed.
        /// </summary>
        public static string Editor_Handedness_Left {
            get {
                return ResourceManager.GetString("Editor.Handedness.Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right handed.
        /// </summary>
        public static string Editor_Handedness_Right {
            get {
                return ResourceManager.GetString("Editor.Handedness.Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument orientation.
        /// </summary>
        public static string Editor_Handedness_Select {
            get {
                return ResourceManager.GetString("Editor.Handedness.Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform.
        /// </summary>
        public static string Editor_MarginMode_All {
            get {
                return ResourceManager.GetString("Editor.MarginMode.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Side.
        /// </summary>
        public static string Editor_MarginMode_BassTreble {
            get {
                return ResourceManager.GetString("Editor.MarginMode.BassTreble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        public static string Editor_MarginMode_Individual {
            get {
                return ResourceManager.GetString("Editor.MarginMode.Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By End.
        /// </summary>
        public static string Editor_MarginMode_NutBridge {
            get {
                return ResourceManager.GetString("Editor.MarginMode.NutBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Frets.
        /// </summary>
        public static string Editor_NumberOfFrets {
            get {
                return ResourceManager.GetString("Editor.NumberOfFrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the total number of frets. Set to zero for fretless instruments. You can also set frets per string in advanced settings..
        /// </summary>
        public static string Editor_NumberOfFrets_Tooltip {
            get {
                return ResourceManager.GetString("Editor.NumberOfFrets.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of strings.
        /// </summary>
        public static string Editor_NumberOfStrings {
            get {
                return ResourceManager.GetString("Editor.NumberOfStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiscale.
        /// </summary>
        public static string Editor_ScaleLengthMode_Multiscale {
            get {
                return ResourceManager.GetString("Editor.ScaleLengthMode.Multiscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different scale lengths for bass and treble strings..
        /// </summary>
        public static string Editor_ScaleLengthMode_Multiscale_Tooltip {
            get {
                return ResourceManager.GetString("Editor.ScaleLengthMode.Multiscale.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per-string.
        /// </summary>
        public static string Editor_ScaleLengthMode_PerString {
            get {
                return ResourceManager.GetString("Editor.ScaleLengthMode.PerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each string can have its own scale length..
        /// </summary>
        public static string Editor_ScaleLengthMode_PerString_Tooltip {
            get {
                return ResourceManager.GetString("Editor.ScaleLengthMode.PerString.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Editor_ScaleLengthMode_Select {
            get {
                return ResourceManager.GetString("Editor.ScaleLengthMode.Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string Editor_ScaleLengthMode_Single {
            get {
                return ResourceManager.GetString("Editor.ScaleLengthMode.Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All strings use the same scale length..
        /// </summary>
        public static string Editor_ScaleLengthMode_Single_Tooltip {
            get {
                return ResourceManager.GetString("Editor.ScaleLengthMode.Single.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string EditStringsDialog_ActionsHeader {
            get {
                return ResourceManager.GetString("EditStringsDialog.ActionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another string to this course.
        /// </summary>
        public static string EditStringsDialog_AddStringTooltip {
            get {
                return ResourceManager.GetString("EditStringsDialog.AddStringTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert this string into a course.
        /// </summary>
        public static string EditStringsDialog_ConvertToCourseTooltip {
            get {
                return ResourceManager.GetString("EditStringsDialog.ConvertToCourseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit spacing between strings in this course.
        /// </summary>
        public static string EditStringsDialog_EditSpacingTooltip {
            get {
                return ResourceManager.GetString("EditStringsDialog.EditSpacingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauge.
        /// </summary>
        public static string EditStringsDialog_GaugeHeader {
            get {
                return ResourceManager.GetString("EditStringsDialog.GaugeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string EditStringsDialog_MaterialHeader {
            get {
                return ResourceManager.GetString("EditStringsDialog.MaterialHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string EditStringsDialog_PreviewHeader {
            get {
                return ResourceManager.GetString("EditStringsDialog.PreviewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this string.
        /// </summary>
        public static string EditStringsDialog_RemoveSingleStringTooltip {
            get {
                return ResourceManager.GetString("EditStringsDialog.RemoveSingleStringTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this string from the course.
        /// </summary>
        public static string EditStringsDialog_RemoveStringFromCourseTooltip {
            get {
                return ResourceManager.GetString("EditStringsDialog.RemoveStringFromCourseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        public static string EditStringsDialog_StringHeader {
            get {
                return ResourceManager.GetString("EditStringsDialog.StringHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string EditTuningDialog_ApplyPresetButton {
            get {
                return ResourceManager.GetString("EditTuningDialog.ApplyPresetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available tunings for this instrument.
        /// </summary>
        public static string EditTuningDialog_NoMatchingTuningsMessage {
            get {
                return ResourceManager.GetString("EditTuningDialog.NoMatchingTuningsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tuning selected.
        /// </summary>
        public static string EditTuningDialog_NoTuningSelectedMessage {
            get {
                return ResourceManager.GetString("EditTuningDialog.NoTuningSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuning is optional and does not change the layout directly. Set it to estimate tension; it is required for fret compensation..
        /// </summary>
        public static string EditTuningDialog_OptionalTuningMessage {
            get {
                return ResourceManager.GetString("EditTuningDialog.OptionalTuningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tension.
        /// </summary>
        public static string EditTuningDialog_TensionHeader {
            get {
                return ResourceManager.GetString("EditTuningDialog.TensionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String tension values are estimated based on tuning, scale length, and string gauge. These are approximate values to help you balance tension across strings..
        /// </summary>
        public static string EditTuningDialog_TensionToolTip {
            get {
                return ResourceManager.GetString("EditTuningDialog.TensionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuning Configuration.
        /// </summary>
        public static string EditTuningDialog_Title {
            get {
                return ResourceManager.GetString("EditTuningDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuning.
        /// </summary>
        public static string EditTuningDialog_TuningHeader {
            get {
                return ResourceManager.GetString("EditTuningDialog.TuningHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available tunings:.
        /// </summary>
        public static string EditTuningDialog_TuningPresetsLabel {
            get {
                return ResourceManager.GetString("EditTuningDialog.TuningPresetsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensate for gauge.
        /// </summary>
        public static string FingerboardEditorPanel_CompensateMarginsLabel {
            get {
                return ResourceManager.GetString("FingerboardEditorPanel.CompensateMarginsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin mode.
        /// </summary>
        public static string FingerboardEditorPanel_DefineMarginsLabel {
            get {
                return ResourceManager.GetString("FingerboardEditorPanel.DefineMarginsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerboard margins.
        /// </summary>
        public static string FingerboardEditorPanel_Header {
            get {
                return ResourceManager.GetString("FingerboardEditorPanel.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge.
        /// </summary>
        public static string FingerboardEnd_Bridge {
            get {
                return ResourceManager.GetString("FingerboardEnd.Bridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nut.
        /// </summary>
        public static string FingerboardEnd_Nut {
            get {
                return ResourceManager.GetString("FingerboardEnd.Nut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bass.
        /// </summary>
        public static string FingerboardSide_Bass {
            get {
                return ResourceManager.GetString("FingerboardSide.Bass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treble.
        /// </summary>
        public static string FingerboardSide_Treble {
            get {
                return ResourceManager.GetString("FingerboardSide.Treble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fret.
        /// </summary>
        public static string FretLabel {
            get {
                return ResourceManager.GetString("FretLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frets.
        /// </summary>
        public static string FretsLabel {
            get {
                return ResourceManager.GetString("FretsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomePage_Title {
            get {
                return ResourceManager.GetString("HomePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design, Customize, and Create Instrument Layouts.
        /// </summary>
        public static string HomePageView_Header {
            get {
                return ResourceManager.GetString("HomePageView.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every fret,.
        /// </summary>
        public static string HomePageView_HeaderPart1 {
            get {
                return ResourceManager.GetString("HomePageView.HeaderPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exactly where it belongs..
        /// </summary>
        public static string HomePageView_HeaderPart2 {
            get {
                return ResourceManager.GetString("HomePageView.HeaderPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECENT FILES.
        /// </summary>
        public static string HomePageView_RecentFilesLabel {
            get {
                return ResourceManager.GetString("HomePageView.RecentFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START FROM A TEMPLATE.
        /// </summary>
        public static string HomePageView_TemplateLabel {
            get {
                return ResourceManager.GetString("HomePageView.TemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design and export precision stringed instrument layouts – from a standard Strat to a fanned-fret 8-string.
        ///Open a recent file or start from a template..
        /// </summary>
        public static string HomePageView_WelcomeText {
            get {
                return ResourceManager.GetString("HomePageView.WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bass.
        /// </summary>
        public static string InstrumentFamily_Bass {
            get {
                return ResourceManager.GetString("InstrumentFamily.Bass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guitar.
        /// </summary>
        public static string InstrumentFamily_Guitar {
            get {
                return ResourceManager.GetString("InstrumentFamily.Guitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument orientation.
        /// </summary>
        public static string InstrumentInfoEditorPanel_Handedness {
            get {
                return ResourceManager.GetString("InstrumentInfoEditorPanel.Handedness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument Info.
        /// </summary>
        public static string InstrumentInfoEditorPanel_Header {
            get {
                return ResourceManager.GetString("InstrumentInfoEditorPanel.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument type.
        /// </summary>
        public static string InstrumentInfoEditorPanel_InstrumentType {
            get {
                return ResourceManager.GetString("InstrumentInfoEditorPanel.InstrumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout name.
        /// </summary>
        public static string InstrumentInfoEditorPanel_LayoutName {
            get {
                return ResourceManager.GetString("InstrumentInfoEditorPanel.LayoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoustic Bass.
        /// </summary>
        public static string InstrumentType_AcousticBass {
            get {
                return ResourceManager.GetString("InstrumentType.AcousticBass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoustic Guitar.
        /// </summary>
        public static string InstrumentType_AcousticGuitar {
            get {
                return ResourceManager.GetString("InstrumentType.AcousticGuitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banjo.
        /// </summary>
        public static string InstrumentType_Banjo {
            get {
                return ResourceManager.GetString("InstrumentType.Banjo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classical Guitar.
        /// </summary>
        public static string InstrumentType_ClassicalGuitar {
            get {
                return ResourceManager.GetString("InstrumentType.ClassicalGuitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string InstrumentType_Custom {
            get {
                return ResourceManager.GetString("InstrumentType.Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Bass.
        /// </summary>
        public static string InstrumentType_ElectricBass {
            get {
                return ResourceManager.GetString("InstrumentType.ElectricBass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Guitar.
        /// </summary>
        public static string InstrumentType_ElectricGuitar {
            get {
                return ResourceManager.GetString("InstrumentType.ElectricGuitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandolin.
        /// </summary>
        public static string InstrumentType_Mandolin {
            get {
                return ResourceManager.GetString("InstrumentType.Mandolin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukulele.
        /// </summary>
        public static string InstrumentType_Ukulele {
            get {
                return ResourceManager.GetString("InstrumentType.Ukulele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blueprint.
        /// </summary>
        public static string LayoutViewerPreset_Blueprint {
            get {
                return ResourceManager.GetString("LayoutViewerPreset.Blueprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string LayoutViewerPreset_Custom {
            get {
                return ResourceManager.GetString("LayoutViewerPreset.Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string LayoutViewerPreset_Dark {
            get {
                return ResourceManager.GetString("LayoutViewerPreset.Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string LayoutViewerPreset_Light {
            get {
                return ResourceManager.GetString("LayoutViewerPreset.Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centerline.
        /// </summary>
        public static string MeasureTool_SnapFilter_CenterLine {
            get {
                return ResourceManager.GetString("MeasureTool.SnapFilter.CenterLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerboard.
        /// </summary>
        public static string MeasureTool_SnapFilter_Fingerboard {
            get {
                return ResourceManager.GetString("MeasureTool.SnapFilter.Fingerboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frets.
        /// </summary>
        public static string MeasureTool_SnapFilter_Frets {
            get {
                return ResourceManager.GetString("MeasureTool.SnapFilter.Frets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strings.
        /// </summary>
        public static string MeasureTool_SnapFilter_Strings {
            get {
                return ResourceManager.GetString("MeasureTool.SnapFilter.Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap to:.
        /// </summary>
        public static string MeasureTool_SnapToLabel {
            get {
                return ResourceManager.GetString("MeasureTool.SnapToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure distances on the layout.
        /// </summary>
        public static string MeasureTool_Tooltip {
            get {
                return ResourceManager.GetString("MeasureTool.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Home Page.
        /// </summary>
        public static string Menu_File_HomePage {
            get {
                return ResourceManager.GetString("Menu_File_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string Menu_File_Open {
            get {
                return ResourceManager.GetString("Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent files.
        /// </summary>
        public static string Menu_File_RecentFiles {
            get {
                return ResourceManager.GetString("Menu_File_RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save....
        /// </summary>
        public static string Menu_File_Save {
            get {
                return ResourceManager.GetString("Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save As....
        /// </summary>
        public static string Menu_File_SaveAs {
            get {
                return ResourceManager.GetString("Menu_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se_ttings....
        /// </summary>
        public static string Menu_File_Settings {
            get {
                return ResourceManager.GetString("Menu_File_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Layout.
        /// </summary>
        public static string NewDocumentName {
            get {
                return ResourceManager.GetString("NewDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file was created with an older version of SiGen and has been automatically migrated. Please review the layout and save the file to update it to the current format..
        /// </summary>
        public static string OpenDocument_FileMigrated_Message {
            get {
                return ResourceManager.GetString("OpenDocument_FileMigrated_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Migrated.
        /// </summary>
        public static string OpenDocument_FileMigrated_Title {
            get {
                return ResourceManager.GetString("OpenDocument_FileMigrated_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be found. It may have been moved, renamed, or deleted.
        ///
        ///{0}.
        /// </summary>
        public static string OpenDocument_FileNotFound_Message {
            get {
                return ResourceManager.GetString("OpenDocument_FileNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        public static string OpenDocument_FileNotFound_Title {
            get {
                return ResourceManager.GetString("OpenDocument_FileNotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be opened. The file may be corrupted or incompatible with this version of SiGen.
        ///
        ///Error: {0}.
        /// </summary>
        public static string OpenDocument_LoadError_Message {
            get {
                return ResourceManager.GetString("OpenDocument_LoadError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Open File.
        /// </summary>
        public static string OpenDocument_LoadError_Title {
            get {
                return ResourceManager.GetString("OpenDocument_LoadError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on a preset to apply.
        /// </summary>
        public static string PresetFlyout_ClickPresetToApply {
            get {
                return ResourceManager.GetString("PresetFlyout.ClickPresetToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale length.
        /// </summary>
        public static string ScaleLength {
            get {
                return ResourceManager.GetString("ScaleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skew.
        /// </summary>
        public static string ScaleLengthEditorPanel_BassTrebleSkew {
            get {
                return ResourceManager.GetString("ScaleLengthEditorPanel.BassTrebleSkew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale length configuration.
        /// </summary>
        public static string ScaleLengthEditorPanel_Header {
            get {
                return ResourceManager.GetString("ScaleLengthEditorPanel.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string ScaleLengthEditorPanel_MultiScaleRatio {
            get {
                return ResourceManager.GetString("ScaleLengthEditorPanel.MultiScaleRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string ScaleLengthEditorPanel_ScaleLengthMode {
            get {
                return ResourceManager.GetString("ScaleLengthEditorPanel.ScaleLengthMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common scale lengths.
        /// </summary>
        public static string ScaleLengthEditorPanel_SingleScalePresetHeader {
            get {
                return ResourceManager.GetString("ScaleLengthEditorPanel.SingleScalePresetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string SettingsDialog_AppearanceSection {
            get {
                return ResourceManager.GetString("SettingsDialog_AppearanceSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Scheme:.
        /// </summary>
        public static string SettingsDialog_ColorSchemeLabel {
            get {
                return ResourceManager.GetString("SettingsDialog_ColorSchemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some UI elements will require an application restart to display in the new language..
        /// </summary>
        public static string SettingsDialog_LanguageChangeMessage {
            get {
                return ResourceManager.GetString("SettingsDialog_LanguageChangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string SettingsDialog_LanguageLabel {
            get {
                return ResourceManager.GetString("SettingsDialog_LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Viewer.
        /// </summary>
        public static string SettingsDialog_LayoutViewerSection {
            get {
                return ResourceManager.GetString("SettingsDialog_LayoutViewerSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string SettingsDialog_ThemeLabel {
            get {
                return ResourceManager.GetString("SettingsDialog_ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsDialog_Title {
            get {
                return ResourceManager.GetString("SettingsDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string SettingsDialog_UnitsSection {
            get {
                return ResourceManager.GetString("SettingsDialog_UnitsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit System:.
        /// </summary>
        public static string SettingsDialog_UnitSystemLabel {
            get {
                return ResourceManager.GetString("SettingsDialog_UnitSystemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a string on the bass side.
        /// </summary>
        public static string StringCountControl_AddBassTooltip {
            get {
                return ResourceManager.GetString("StringCountControl_AddBassTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a string on the treble side.
        /// </summary>
        public static string StringCountControl_AddTrebleTooltip {
            get {
                return ResourceManager.GetString("StringCountControl_AddTrebleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a string from the bass side.
        /// </summary>
        public static string StringCountControl_RemoveBassTooltip {
            get {
                return ResourceManager.GetString("StringCountControl_RemoveBassTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a string from the treble side.
        /// </summary>
        public static string StringCountControl_RemoveTrebleTooltip {
            get {
                return ResourceManager.GetString("StringCountControl_RemoveTrebleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        public static string StringLabel {
            get {
                return ResourceManager.GetString("StringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze Wound.
        /// </summary>
        public static string StringMaterialType_BronzeWound {
            get {
                return ResourceManager.GetString("StringMaterialType.BronzeWound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickel Wound.
        /// </summary>
        public static string StringMaterialType_NickelWound {
            get {
                return ResourceManager.GetString("StringMaterialType.NickelWound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Nylon.
        /// </summary>
        public static string StringMaterialType_NylonPlain {
            get {
                return ResourceManager.GetString("StringMaterialType.NylonPlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver Plated Wound.
        /// </summary>
        public static string StringMaterialType_SilverPlatedWound {
            get {
                return ResourceManager.GetString("StringMaterialType.SilverPlatedWound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Steel.
        /// </summary>
        public static string StringMaterialType_SteelPlain {
            get {
                return ResourceManager.GetString("StringMaterialType.SteelPlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        public static string StringsFretsEditorPanel_AdvancedSettings {
            get {
                return ResourceManager.GetString("StringsFretsEditorPanel.AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common number of frets.
        /// </summary>
        public static string StringsFretsEditorPanel_CommonFretsPresetHeader {
            get {
                return ResourceManager.GetString("StringsFretsEditorPanel.CommonFretsPresetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure number of frets and temperament per string.
        /// </summary>
        public static string StringsFretsEditorPanel_EditFretsTooltip {
            get {
                return ResourceManager.GetString("StringsFretsEditorPanel.EditFretsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure string gauge and material for each string.
        /// </summary>
        public static string StringsFretsEditorPanel_EditStringsTooltip {
            get {
                return ResourceManager.GetString("StringsFretsEditorPanel.EditStringsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set tuning for each string and estimate tension.
        /// </summary>
        public static string StringsFretsEditorPanel_EditTuningTooltip {
            get {
                return ResourceManager.GetString("StringsFretsEditorPanel.EditTuningTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strings &amp; Frets.
        /// </summary>
        public static string StringsFretsEditorPanel_Header {
            get {
                return ResourceManager.GetString("StringsFretsEditorPanel.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of frets.
        /// </summary>
        public static string StringsFretsEditorPanel_NumberOfFrets {
            get {
                return ResourceManager.GetString("StringsFretsEditorPanel.NumberOfFrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of strings.
        /// </summary>
        public static string StringsFretsEditorPanel_NumberOfStrings {
            get {
                return ResourceManager.GetString("StringsFretsEditorPanel.NumberOfStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strings.
        /// </summary>
        public static string StringsLabel {
            get {
                return ResourceManager.GetString("StringsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String spacing at the {0}.
        /// </summary>
        public static string StringSpacingDialog_TitleFormat {
            get {
                return ResourceManager.GetString("StringSpacingDialog.TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge spacing.
        /// </summary>
        public static string StringSpacingEditorPanel_BridgeSpacing {
            get {
                return ResourceManager.GetString("StringSpacingEditorPanel.BridgeSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centering.
        /// </summary>
        public static string StringSpacingEditorPanel_CenterAlignment {
            get {
                return ResourceManager.GetString("StringSpacingEditorPanel.CenterAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure….
        /// </summary>
        public static string StringSpacingEditorPanel_ConfigureSpacingButton {
            get {
                return ResourceManager.GetString("StringSpacingEditorPanel.ConfigureSpacingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Spacing &amp; Layout.
        /// </summary>
        public static string StringSpacingEditorPanel_Header {
            get {
                return ResourceManager.GetString("StringSpacingEditorPanel.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nut spacing.
        /// </summary>
        public static string StringSpacingEditorPanel_NutSpacing {
            get {
                return ResourceManager.GetString("StringSpacingEditorPanel.NutSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing.
        /// </summary>
        public static string StringSpacingEditorPanel_SpacingHeader {
            get {
                return ResourceManager.GetString("StringSpacingEditorPanel.SpacingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string StringSpacingEditorPanel_SpacingMode {
            get {
                return ResourceManager.GetString("StringSpacingEditorPanel.SpacingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common spacings.
        /// </summary>
        public static string StringSpacingEditorPanel_SpacingPresetHeader {
            get {
                return ResourceManager.GetString("StringSpacingEditorPanel.SpacingPresetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total spread.
        /// </summary>
        public static string StringSpacingEditorPanel_SpreadHeader {
            get {
                return ResourceManager.GetString("StringSpacingEditorPanel.SpreadHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balanced.
        /// </summary>
        public static string TensionBalanceState_Balanced {
            get {
                return ResourceManager.GetString("TensionBalanceState.Balanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over-tensioned.
        /// </summary>
        public static string TensionBalanceState_OverTensioned {
            get {
                return ResourceManager.GetString("TensionBalanceState.OverTensioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under-tensioned.
        /// </summary>
        public static string TensionBalanceState_UnderTensioned {
            get {
                return ResourceManager.GetString("TensionBalanceState.UnderTensioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string TensionBalanceState_Unknown {
            get {
                return ResourceManager.GetString("TensionBalanceState.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperial.
        /// </summary>
        public static string UnitSystem_Imperial {
            get {
                return ResourceManager.GetString("UnitSystem.Imperial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric.
        /// </summary>
        public static string UnitSystem_Metric {
            get {
                return ResourceManager.GetString("UnitSystem.Metric", resourceCulture);
            }
        }
    }
}
