//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGen.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiGen.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string CourseLabel {
            get {
                return ResourceManager.GetString("CourseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today {0}.
        /// </summary>
        public static string DateLabel_Today {
            get {
                return ResourceManager.GetString("DateLabel.Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday {0}.
        /// </summary>
        public static string DateLabel_Yesterday {
            get {
                return ResourceManager.GetString("DateLabel.Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left handed.
        /// </summary>
        public static string Editor_Handedness_Left {
            get {
                return ResourceManager.GetString("Editor.Handedness.Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right handed.
        /// </summary>
        public static string Editor_Handedness_Right {
            get {
                return ResourceManager.GetString("Editor.Handedness.Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument orientation.
        /// </summary>
        public static string Editor_Handedness_Select {
            get {
                return ResourceManager.GetString("Editor.Handedness.Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform.
        /// </summary>
        public static string Editor_MarginMode_All {
            get {
                return ResourceManager.GetString("Editor.MarginMode.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Side.
        /// </summary>
        public static string Editor_MarginMode_BassTreble {
            get {
                return ResourceManager.GetString("Editor.MarginMode.BassTreble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        public static string Editor_MarginMode_Individual {
            get {
                return ResourceManager.GetString("Editor.MarginMode.Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By End.
        /// </summary>
        public static string Editor_MarginMode_NutBridge {
            get {
                return ResourceManager.GetString("Editor.MarginMode.NutBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Frets.
        /// </summary>
        public static string Editor_NumberOfFrets {
            get {
                return ResourceManager.GetString("Editor.NumberOfFrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the total number of frets. Set to zero for fretless instruments. You can also set frets per string in advanced settings..
        /// </summary>
        public static string Editor_NumberOfFrets_Tooltip {
            get {
                return ResourceManager.GetString("Editor.NumberOfFrets.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of strings.
        /// </summary>
        public static string Editor_NumberOfStrings {
            get {
                return ResourceManager.GetString("Editor.NumberOfStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiscale.
        /// </summary>
        public static string Editor_ScaleLengthMode_Multiscale {
            get {
                return ResourceManager.GetString("Editor.ScaleLengthMode.Multiscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different scale lengths for bass and treble strings..
        /// </summary>
        public static string Editor_ScaleLengthMode_Multiscale_Tooltip {
            get {
                return ResourceManager.GetString("Editor.ScaleLengthMode.Multiscale.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per-string.
        /// </summary>
        public static string Editor_ScaleLengthMode_PerString {
            get {
                return ResourceManager.GetString("Editor.ScaleLengthMode.PerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each string can have its own scale length..
        /// </summary>
        public static string Editor_ScaleLengthMode_PerString_Tooltip {
            get {
                return ResourceManager.GetString("Editor.ScaleLengthMode.PerString.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Editor_ScaleLengthMode_Select {
            get {
                return ResourceManager.GetString("Editor.ScaleLengthMode.Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string Editor_ScaleLengthMode_Single {
            get {
                return ResourceManager.GetString("Editor.ScaleLengthMode.Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All strings use the same scale length..
        /// </summary>
        public static string Editor_ScaleLengthMode_Single_Tooltip {
            get {
                return ResourceManager.GetString("Editor.ScaleLengthMode.Single.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string EditTuningDialog_ApplyPresetButton {
            get {
                return ResourceManager.GetString("EditTuningDialog.ApplyPresetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available tunings for this instrument.
        /// </summary>
        public static string EditTuningDialog_NoMatchingTuningsMessage {
            get {
                return ResourceManager.GetString("EditTuningDialog.NoMatchingTuningsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tuning selected.
        /// </summary>
        public static string EditTuningDialog_NoTuningSelectedMessage {
            get {
                return ResourceManager.GetString("EditTuningDialog.NoTuningSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuning is optional and does not change the layout directly. Set it to estimate tension; it is required for fret compensation..
        /// </summary>
        public static string EditTuningDialog_OptionalTuningMessage {
            get {
                return ResourceManager.GetString("EditTuningDialog.OptionalTuningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuning Configuration.
        /// </summary>
        public static string EditTuningDialog_Title {
            get {
                return ResourceManager.GetString("EditTuningDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available tunings:.
        /// </summary>
        public static string EditTuningDialog_TuningPresetsLabel {
            get {
                return ResourceManager.GetString("EditTuningDialog.TuningPresetsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensate for gauge.
        /// </summary>
        public static string FingerboardEditorPanel_CompensateMarginsLabel {
            get {
                return ResourceManager.GetString("FingerboardEditorPanel.CompensateMarginsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin mode.
        /// </summary>
        public static string FingerboardEditorPanel_DefineMarginsLabel {
            get {
                return ResourceManager.GetString("FingerboardEditorPanel.DefineMarginsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerboard margins.
        /// </summary>
        public static string FingerboardEditorPanel_Header {
            get {
                return ResourceManager.GetString("FingerboardEditorPanel.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge.
        /// </summary>
        public static string FingerboardEnd_Bridge {
            get {
                return ResourceManager.GetString("FingerboardEnd.Bridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nut.
        /// </summary>
        public static string FingerboardEnd_Nut {
            get {
                return ResourceManager.GetString("FingerboardEnd.Nut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bass.
        /// </summary>
        public static string FingerboardSide_Bass {
            get {
                return ResourceManager.GetString("FingerboardSide.Bass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treble.
        /// </summary>
        public static string FingerboardSide_Treble {
            get {
                return ResourceManager.GetString("FingerboardSide.Treble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fret.
        /// </summary>
        public static string FretLabel {
            get {
                return ResourceManager.GetString("FretLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frets.
        /// </summary>
        public static string FretsLabel {
            get {
                return ResourceManager.GetString("FretsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design, Customize, and Create Instrument Layouts.
        /// </summary>
        public static string HomePageView_Header {
            get {
                return ResourceManager.GetString("HomePageView.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every fret,.
        /// </summary>
        public static string HomePageView_HeaderPart1 {
            get {
                return ResourceManager.GetString("HomePageView.HeaderPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exactly where it belongs..
        /// </summary>
        public static string HomePageView_HeaderPart2 {
            get {
                return ResourceManager.GetString("HomePageView.HeaderPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECENT FILES.
        /// </summary>
        public static string HomePageView_RecentFilesLabel {
            get {
                return ResourceManager.GetString("HomePageView.RecentFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START FROM A TEMPLATE.
        /// </summary>
        public static string HomePageView_TemplateLabel {
            get {
                return ResourceManager.GetString("HomePageView.TemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design and export precision stringed instrument layouts — from a standard Strat to a fanned-fret 8-string.
        ///Open a recent file or start from a template..
        /// </summary>
        public static string HomePageView_WelcomeText {
            get {
                return ResourceManager.GetString("HomePageView.WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bass.
        /// </summary>
        public static string InstrumentFamily_Bass {
            get {
                return ResourceManager.GetString("InstrumentFamily.Bass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guitar.
        /// </summary>
        public static string InstrumentFamily_Guitar {
            get {
                return ResourceManager.GetString("InstrumentFamily.Guitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument orientation.
        /// </summary>
        public static string InstrumentInfoEditorPanel_Handedness {
            get {
                return ResourceManager.GetString("InstrumentInfoEditorPanel.Handedness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument Info.
        /// </summary>
        public static string InstrumentInfoEditorPanel_Header {
            get {
                return ResourceManager.GetString("InstrumentInfoEditorPanel.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument type.
        /// </summary>
        public static string InstrumentInfoEditorPanel_InstrumentType {
            get {
                return ResourceManager.GetString("InstrumentInfoEditorPanel.InstrumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout name.
        /// </summary>
        public static string InstrumentInfoEditorPanel_LayoutName {
            get {
                return ResourceManager.GetString("InstrumentInfoEditorPanel.LayoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoustic Bass.
        /// </summary>
        public static string InstrumentType_AcousticBass {
            get {
                return ResourceManager.GetString("InstrumentType.AcousticBass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoustic Guitar.
        /// </summary>
        public static string InstrumentType_AcousticGuitar {
            get {
                return ResourceManager.GetString("InstrumentType.AcousticGuitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banjo.
        /// </summary>
        public static string InstrumentType_Banjo {
            get {
                return ResourceManager.GetString("InstrumentType.Banjo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classical Guitar.
        /// </summary>
        public static string InstrumentType_ClassicalGuitar {
            get {
                return ResourceManager.GetString("InstrumentType.ClassicalGuitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string InstrumentType_Custom {
            get {
                return ResourceManager.GetString("InstrumentType.Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Bass.
        /// </summary>
        public static string InstrumentType_ElectricBass {
            get {
                return ResourceManager.GetString("InstrumentType.ElectricBass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Guitar.
        /// </summary>
        public static string InstrumentType_ElectricGuitar {
            get {
                return ResourceManager.GetString("InstrumentType.ElectricGuitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandolin.
        /// </summary>
        public static string InstrumentType_Mandolin {
            get {
                return ResourceManager.GetString("InstrumentType.Mandolin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukulele.
        /// </summary>
        public static string InstrumentType_Ukulele {
            get {
                return ResourceManager.GetString("InstrumentType.Ukulele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Layout.
        /// </summary>
        public static string NewDocumentName {
            get {
                return ResourceManager.GetString("NewDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on a preset to apply.
        /// </summary>
        public static string PresetFlyout_ClickPresetToApply {
            get {
                return ResourceManager.GetString("PresetFlyout.ClickPresetToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale length.
        /// </summary>
        public static string ScaleLength {
            get {
                return ResourceManager.GetString("ScaleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skew.
        /// </summary>
        public static string ScaleLengthEditorPanel_BassTrebleSkew {
            get {
                return ResourceManager.GetString("ScaleLengthEditorPanel.BassTrebleSkew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale length configuration.
        /// </summary>
        public static string ScaleLengthEditorPanel_Header {
            get {
                return ResourceManager.GetString("ScaleLengthEditorPanel.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string ScaleLengthEditorPanel_MultiScaleRatio {
            get {
                return ResourceManager.GetString("ScaleLengthEditorPanel.MultiScaleRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string ScaleLengthEditorPanel_ScaleLengthMode {
            get {
                return ResourceManager.GetString("ScaleLengthEditorPanel.ScaleLengthMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common scale lengths.
        /// </summary>
        public static string ScaleLengthEditorPanel_SingleScalePresetHeader {
            get {
                return ResourceManager.GetString("ScaleLengthEditorPanel.SingleScalePresetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a string on the bass side.
        /// </summary>
        public static string StringCountControl_AddBassTooltip {
            get {
                return ResourceManager.GetString("StringCountControl_AddBassTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a string on the treble side.
        /// </summary>
        public static string StringCountControl_AddTrebleTooltip {
            get {
                return ResourceManager.GetString("StringCountControl_AddTrebleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a string from the bass side.
        /// </summary>
        public static string StringCountControl_RemoveBassTooltip {
            get {
                return ResourceManager.GetString("StringCountControl_RemoveBassTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a string from the treble side.
        /// </summary>
        public static string StringCountControl_RemoveTrebleTooltip {
            get {
                return ResourceManager.GetString("StringCountControl_RemoveTrebleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String course.
        /// </summary>
        public static string StringCourseLabel {
            get {
                return ResourceManager.GetString("StringCourseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String group.
        /// </summary>
        public static string StringGroupLabel {
            get {
                return ResourceManager.GetString("StringGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        public static string StringLabel {
            get {
                return ResourceManager.GetString("StringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common number of frets.
        /// </summary>
        public static string StringsFretsEditorPanel_CommonFretsPresetHeader {
            get {
                return ResourceManager.GetString("StringsFretsEditorPanel.CommonFretsPresetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strings &amp; Frets.
        /// </summary>
        public static string StringsFretsEditorPanel_Header {
            get {
                return ResourceManager.GetString("StringsFretsEditorPanel.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of frets.
        /// </summary>
        public static string StringsFretsEditorPanel_NumberOfFrets {
            get {
                return ResourceManager.GetString("StringsFretsEditorPanel.NumberOfFrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of strings.
        /// </summary>
        public static string StringsFretsEditorPanel_NumberOfStrings {
            get {
                return ResourceManager.GetString("StringsFretsEditorPanel.NumberOfStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strings.
        /// </summary>
        public static string StringsLabel {
            get {
                return ResourceManager.GetString("StringsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String spacing at the {0}.
        /// </summary>
        public static string StringSpacingDialog_TitleFormat {
            get {
                return ResourceManager.GetString("StringSpacingDialog.TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge spacing.
        /// </summary>
        public static string StringSpacingEditorPanel_BridgeSpacing {
            get {
                return ResourceManager.GetString("StringSpacingEditorPanel.BridgeSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centering.
        /// </summary>
        public static string StringSpacingEditorPanel_CenterAlignment {
            get {
                return ResourceManager.GetString("StringSpacingEditorPanel.CenterAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure….
        /// </summary>
        public static string StringSpacingEditorPanel_ConfigureSpacingButton {
            get {
                return ResourceManager.GetString("StringSpacingEditorPanel.ConfigureSpacingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Spacing &amp; Layout.
        /// </summary>
        public static string StringSpacingEditorPanel_Header {
            get {
                return ResourceManager.GetString("StringSpacingEditorPanel.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nut spacing.
        /// </summary>
        public static string StringSpacingEditorPanel_NutSpacing {
            get {
                return ResourceManager.GetString("StringSpacingEditorPanel.NutSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing.
        /// </summary>
        public static string StringSpacingEditorPanel_SpacingHeader {
            get {
                return ResourceManager.GetString("StringSpacingEditorPanel.SpacingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string StringSpacingEditorPanel_SpacingMode {
            get {
                return ResourceManager.GetString("StringSpacingEditorPanel.SpacingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common spacings.
        /// </summary>
        public static string StringSpacingEditorPanel_SpacingPresetHeader {
            get {
                return ResourceManager.GetString("StringSpacingEditorPanel.SpacingPresetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total spread.
        /// </summary>
        public static string StringSpacingEditorPanel_SpreadHeader {
            get {
                return ResourceManager.GetString("StringSpacingEditorPanel.SpreadHeader", resourceCulture);
            }
        }
    }
}
