//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGen.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiGen.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left handed.
        /// </summary>
        public static string Editor_Handedness_Left {
            get {
                return ResourceManager.GetString("Editor.Handedness.Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right handed.
        /// </summary>
        public static string Editor_Handedness_Right {
            get {
                return ResourceManager.GetString("Editor.Handedness.Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument orientation.
        /// </summary>
        public static string Editor_Handedness_Select {
            get {
                return ResourceManager.GetString("Editor.Handedness.Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select whether the instrument layout is for a right-handed or left-handed player..
        /// </summary>
        public static string Editor_Handedness_Tooltip {
            get {
                return ResourceManager.GetString("Editor.Handedness.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument Type.
        /// </summary>
        public static string Editor_InstrumentType {
            get {
                return ResourceManager.GetString("Editor.InstrumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the instrument type (e.g., Electric Guitar, Bass, Banjo). This affects default values and available options..
        /// </summary>
        public static string Editor_InstrumentType_Tooltip {
            get {
                return ResourceManager.GetString("Editor.InstrumentType.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Frets.
        /// </summary>
        public static string Editor_NumberOfFrets {
            get {
                return ResourceManager.GetString("Editor.NumberOfFrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the total number of frets. Set to zero for fretless instruments. You can also set frets per string in advanced settings..
        /// </summary>
        public static string Editor_NumberOfFrets_Tooltip {
            get {
                return ResourceManager.GetString("Editor.NumberOfFrets.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of strings.
        /// </summary>
        public static string Editor_NumberOfStrings {
            get {
                return ResourceManager.GetString("Editor.NumberOfStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the total number of strings for your instrument..
        /// </summary>
        public static string Editor_NumberOfStrings_Tooltip {
            get {
                return ResourceManager.GetString("Editor.NumberOfStrings.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiscale.
        /// </summary>
        public static string Editor_ScaleLengthMode_Multiscale {
            get {
                return ResourceManager.GetString("Editor.ScaleLengthMode.Multiscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different scale lengths for bass and treble strings..
        /// </summary>
        public static string Editor_ScaleLengthMode_Multiscale_Tooltip {
            get {
                return ResourceManager.GetString("Editor.ScaleLengthMode.Multiscale.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per-string.
        /// </summary>
        public static string Editor_ScaleLengthMode_PerString {
            get {
                return ResourceManager.GetString("Editor.ScaleLengthMode.PerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each string can have its own scale length..
        /// </summary>
        public static string Editor_ScaleLengthMode_PerString_Tooltip {
            get {
                return ResourceManager.GetString("Editor.ScaleLengthMode.PerString.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Length Mode.
        /// </summary>
        public static string Editor_ScaleLengthMode_Select {
            get {
                return ResourceManager.GetString("Editor.ScaleLengthMode.Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string Editor_ScaleLengthMode_Single {
            get {
                return ResourceManager.GetString("Editor.ScaleLengthMode.Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All strings use the same scale length..
        /// </summary>
        public static string Editor_ScaleLengthMode_Single_Tooltip {
            get {
                return ResourceManager.GetString("Editor.ScaleLengthMode.Single.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bass.
        /// </summary>
        public static string FingerboardSide_Bass {
            get {
                return ResourceManager.GetString("FingerboardSide.Bass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treble.
        /// </summary>
        public static string FingerboardSide_Treble {
            get {
                return ResourceManager.GetString("FingerboardSide.Treble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bass.
        /// </summary>
        public static string InstrumentFamilly_Bass {
            get {
                return ResourceManager.GetString("InstrumentFamilly.Bass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guitar.
        /// </summary>
        public static string InstrumentFamilly_Guitar {
            get {
                return ResourceManager.GetString("InstrumentFamilly.Guitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoustic Bass.
        /// </summary>
        public static string InstrumentType_AcousticBass {
            get {
                return ResourceManager.GetString("InstrumentType.AcousticBass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoustic Guitar.
        /// </summary>
        public static string InstrumentType_AcousticGuitar {
            get {
                return ResourceManager.GetString("InstrumentType.AcousticGuitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banjo.
        /// </summary>
        public static string InstrumentType_Banjo {
            get {
                return ResourceManager.GetString("InstrumentType.Banjo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Bass.
        /// </summary>
        public static string InstrumentType_BassGuitar {
            get {
                return ResourceManager.GetString("InstrumentType.BassGuitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classical Guitar.
        /// </summary>
        public static string InstrumentType_ClassicalGuitar {
            get {
                return ResourceManager.GetString("InstrumentType.ClassicalGuitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string InstrumentType_Custom {
            get {
                return ResourceManager.GetString("InstrumentType.Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Guitar.
        /// </summary>
        public static string InstrumentType_ElectricGuitar {
            get {
                return ResourceManager.GetString("InstrumentType.ElectricGuitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandolin.
        /// </summary>
        public static string InstrumentType_Mandolin {
            get {
                return ResourceManager.GetString("InstrumentType.Mandolin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukulele.
        /// </summary>
        public static string InstrumentType_Ukulele {
            get {
                return ResourceManager.GetString("InstrumentType.Ukulele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Length.
        /// </summary>
        public static string ScaleLength {
            get {
                return ResourceManager.GetString("ScaleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a string on the bass side.
        /// </summary>
        public static string StringCountControl_AddBassTooltip {
            get {
                return ResourceManager.GetString("StringCountControl_AddBassTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a string on the treble side.
        /// </summary>
        public static string StringCountControl_AddTrebleTooltip {
            get {
                return ResourceManager.GetString("StringCountControl_AddTrebleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a string from the bass side.
        /// </summary>
        public static string StringCountControl_RemoveBassTooltip {
            get {
                return ResourceManager.GetString("StringCountControl_RemoveBassTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a string from the treble side.
        /// </summary>
        public static string StringCountControl_RemoveTrebleTooltip {
            get {
                return ResourceManager.GetString("StringCountControl_RemoveTrebleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        public static string StringLabel {
            get {
                return ResourceManager.GetString("StringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strings.
        /// </summary>
        public static string StringsLabel {
            get {
                return ResourceManager.GetString("StringsLabel", resourceCulture);
            }
        }
    }
}
