// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiGen.Data.Entities;

#nullable disable

namespace SiGen.Migrations
{
    [DbContext(typeof(SiGenDbContext))]
    [Migration("20260204191717_StringSets")]
    partial class StringSets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("SiGen.Data.Entities.SetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StringSetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StringSpecId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StringSetId");

                    b.HasIndex("StringSpecId");

                    b.ToTable("StringSetItems", (string)null);
                });

            modelBuilder.Entity("SiGen.Data.Entities.StringSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstrumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfStrings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StringSets", (string)null);
                });

            modelBuilder.Entity("SiGen.Data.Entities.StringSpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<double?>("CoreDiameter")
                        .HasColumnType("REAL");

                    b.Property<double>("Gauge")
                        .HasColumnType("REAL");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double?>("UnitWeight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("StringSpecs", (string)null);
                });

            modelBuilder.Entity("SiGen.Data.Entities.SetItem", b =>
                {
                    b.HasOne("SiGen.Data.Entities.StringSet", "StringSet")
                        .WithMany("Strings")
                        .HasForeignKey("StringSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiGen.Data.Entities.StringSpec", "String")
                        .WithMany()
                        .HasForeignKey("StringSpecId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("String");

                    b.Navigation("StringSet");
                });

            modelBuilder.Entity("SiGen.Data.Entities.StringSet", b =>
                {
                    b.Navigation("Strings");
                });
#pragma warning restore 612, 618
        }
    }
}
